### ISSUE TITLE
Compiler warning in mpz_int128.h

### ISSUE THREAD

**Issue by jsteube** [jsteube/princeprocessor#21]
@magnumripper See here:

mpz_int128.h: In function ‘_mpz_set_str’:
mpz_int128.h:116:2: warning: implicit declaration of function ‘strncasecmp’ [-Wimplicit-function-declaration]
  if (!strncasecmp(str, "0x", 2)) {

I'm using gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by magnumripper** [comment]
It's a compiler bug. It disappears with less than -O2 or if you put a debug print in there :-) I bet it's not present in gcc-4.7 (but I know it's present in gcc-4.9).

https://github.com/magnumripper/JohnTheRipper/issues/1029

**Comment by magnumripper** [comment]
Oh, wait I'm confused, lol. I thought you meant another warning.
