### ISSUE TITLE
Possible Bug "is hashcat running"

### ISSUE THREAD

**Issue by dropdeadfu** [jsteube/princeprocessor#37]
When I run a bulk attack with --runtime in hashcat I realized that after hashcat stopped with the timelimit prince still keeps on running.

I can reproduce this under win8.1

**Comment by Sc00bz** [comment]
https://github.com/jsteube/princeprocessor/pull/39 should fix this problem.

**Comment by dropdeadfu** [comment]
Works perfectly now, thanks scoobz!
