### ISSUE TITLE
Print position when stopped (or stdout closed)

### ISSUE THREAD

**Issue by magnumripper** [jsteube/princeprocessor#42]
We should consider printing the position to stderr when aborting, so user can resume with --skip if she wants to. Preferably with some margin, eg. not counting the current inner loop.

**Comment by jsteube** [comment]
That's a good idea. We're doing this with hashcat CPU the same way. However, many user complain that this information should have been written to a file rather than to stderr.

**Comment by jsteube** [comment]
Added to https://github.com/jsteube/princeprocessor/commit/f662d8d2b798da608695531169c9fb9fc67bab6f
