### ISSUE TITLE
wrong validation of specific skip limit option

### ISSUE THREAD

**Issue by ryabkov** [jsteube/princeprocessor#45]
When I try to set limit=0 or skip=0 (than see that mpz_set_str not implemented...)
But when I try to set limit=0x0 or skip=0x0 then everything ok...

i think that function _mpz_set_str  have a little bug... (or feature?)

**Comment by jsteube** [comment]
Should be fixed with: https://github.com/jsteube/princeprocessor/commit/784704333be1e2b8ebd9b21b0e6a0ab04cc0821f
