### ISSUE TITLE
-l, --limit description is wrong

### ISSUE THREAD

**Issue by Sc00bz** [jsteube/princeprocessor#6]
Limit is described as stop at a specific position.
https://github.com/jsteube/princeprocessor/blob/1b46d1d335e953a764fccaa8812dc9ed50d79a30/src/pp.c#L158

But it is used to output a specific number of passwords.
https://github.com/jsteube/princeprocessor/blob/1b46d1d335e953a764fccaa8812dc9ed50d79a30/src/pp.c#L815

"pp -s 20 -l 10" skips the first 20 then outputs the next 10, but according to the description it shouldn't output anything.

**Comment by jsteube** [comment]
Thanks for report! Should be fixed
